select * FROM FAMILY.INFO;
SELECT CHILD.NAME AS CHILD_NAME
,CHILD.AGE AS CHILD_AGE
,PARENT.NAME AS PARENT_NAME
,PARENT.AGE AS PARENT_AGE
FROM FAMILY.INFO AS CHILD
JOIN FAMILY.INFO AS PARENT ON CHILD.PARENT_ID=PARENT.MEMBER_ID;


